## <p style="text-align: center;">NSI - Éléments de programmation</p>
## <p style="text-align: center;">Ensembles et dictionnaires</p>
## <p style="text-align: center;">Lycée Beaussier - F. Lagrave</p>

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/Fklag/NSI_iere/master?filepath=11_Elements_programmation_diapo.ipynb)

# Supports de cours

<div id="top">
    
### Un point sur le cours  
    
Nous avons vu :   
1. Les <a href="http://lycee.lagrave.free.fr/nsi/programmation/0_Elements_programmation_diapo.pdf" target="_blank">éléments de bases</a> d'un langage
   * Les <a href="http://lycee.lagrave.free.fr/nsi/programmation/0_Elements_programmation_diapo.pdf" target="_blank">expressions (arithmétiques)</a>  
   * La <a href="http://lycee.lagrave.free.fr/nsi/programmation/0_Elements_programmation_diapo.pdf" target="_blank">définition de fonctions</a>  
   * L'<a href="http://lycee.lagrave.free.fr/nsi/programmation/4_Elements_programmation_diapo.pdf" target="_blank">affectation de variables</a>  
   * Les <a href="http://lycee.lagrave.free.fr/nsi/programmation/4_Elements_programmation_diapo.pdf" target="_blank">séquences d'instructions </a> 
   * Les <a href="http://lycee.lagrave.free.fr/nsi/programmation/4_Elements_programmation_diapo.pdf" target="_blank">alternatives</a>  
   * Les <a href="http://lycee.lagrave.free.fr/nsi/programmation/5_Elements_programmation_diapo.pdf" target="_blank">boucles</a>  
   
2. Un type de structure de données : les **séquences**  
   * les intervalles : <a href="http://lycee.lagrave.free.fr/nsi/programmation/7_Elements_programmation_diapo.pdf" target="_blank">séquences d'entiers</a>  
   * les chaı̂nes de caractères : <a href="http://lycee.lagrave.free.fr/nsi/programmation/7_Elements_programmation_diapo.pdf" target="_blank">séquences de caractères</a> 
   * les **listes** : <a href="http://lycee.lagrave.free.fr/nsi/programmation/8_Elements_programmation_diapo.pdf" target="_blank">séquences génériques</a>  

→ Point commun : **l'ordre est important !**
    

</div>

###   Un deuxième type de structure de données : les données itérables  
• les **ensembles** qui sont l'équivalent informatique des ensembles mathématiques  
• les **dictionnaires** qui associent des **clés** de recherche à des **valeurs**. 
    
**Plan du cours**  
    
1.   Les ensembles 
     Opérations de base  
     Itération  
     Test d'égalité  
     Opérations ensemblistes  
2.   Les dictionnaires  
     Opérations de base
     Itération  
3.   Un exemple complet

### Notion d’ensemble  

La notion d'ensemble est fondamentale en mathématique.  
De fait, l'essentiel des constructions mathématiques sont basées sur *<a href="https://fr.wikipedia.org/wiki/Th%C3%A9orie_des_ensembles" target="_blank">la théorie des ensembles</a>*.

Un ensemble désigne intuitivement **une collection d'objets** (les éléments de l'ensemble).  

En tant que structure de donnée :  
  * collection de valeurs (au même titre qu'une liste)  
  * **sans doublons**
  * **sans ordre**
  
Comme toute structure de données, elle est munie :
  * d'un type : $\texttt{set}[\texttt{<type>}]$  
  * de primitives permettant de manipuler la structure  
    - opération habituelles :  
      • construction : $\texttt{set}$ , $\left\{\ldots\right\}$  
      • ajout d'éléments : $\texttt{add}$  
      • test d'égalité : $\texttt{==}$  
      • test appartenance : $\texttt{in}$  
    - opération spécifiques :  
      • intersection d'ensembles : $\texttt{\&}$  
      • union d'ensembles : $\texttt{|}$  
      • différences : $\texttt{--}$  

### Définition   
Pour notre cours, nous adopterons la définition suivante.    
**Définition :**  un ensemble de $\texttt{type} \, \texttt{set}[\alpha]$ est une collection d'éléments de $\texttt{type}\, \alpha$ et tous distincts (au sens de l'égalité de $\texttt{Python} ==$)  

Pour des raisons techniques, **le $\texttt{type} \, \alpha$** des éléments d'un ensemble doit être **immutable**.  
À l'exception des listes et des ensembles eux-mêmes, tous les types que nous avons vus répondent à cette contrainte.  

On retiendra donc : **Aucun type $\texttt{liste}$ ou $\texttt{ensemble}$ ne peut apparaître dans le $\alpha$ de $\texttt{set}[\alpha]$**.  


> Puisqu'un programmeur (même confirmé) doit maîtriser le type des informations qu'il manipule, 
nous instituons comme pour les listes la règle du typage explicite et précis des éléments d'un ensemble.  
**À retenir :** c'est au programmeur (donc à vous) qu'incombe la responsabilité de garantir que
les éléments contenus dans un ensemble de $\texttt{type} \, \texttt{set}[\alpha]$ soient bien tous du même **$\texttt{type} \, \alpha$**

### Construction d'un ensemble  
* Construction explicite: on énonce tous les éléments  $\left\{ e_1, e_2, \ldots, e_N \right\}$  
  * les  $e_1$, $e_2$, $\ldots$, $e_N$ : expressions de $\texttt{type}\, \alpha$  
* Construction de l'ensemble vide $\, \texttt{set}( \,)$  
  * Pour des raisons historiques , la notation $\, \left\{ \, \right\}$ est en effet réservée aux dictionnaires vides   
    (mais pour éviter toute ambiguïté nous utiliserons plutôt $\, \texttt{dict}(\,)$, cf. deuxième partie du cours).
* Exemples

In [1]:
{42, 11, 38} # set[int]

{11, 38, 42}

In [2]:
type({42, 11, 38}) # set[int]

set

In [3]:
{2*3*7, 10+1 , (27+6)+5} # set[int]

{11, 38, 42}

In [4]:
import math
{math.pi, 5.0/3.0, 11.38, math.sin(math.pi/4)} # set[float]

{0.7071067811865475, 1.6666666666666667, 3.141592653589793, 11.38}

### Construction d’un ensemble  
Important  
* les éléments dans un ensemble doivent être du **même $\texttt{type}$**   
  - c'est au programmeur de le garantir  
  - il faut donc y veiller lors de la construction  
* un ensemble **ne doit pas contenir 2 fois** le même élément  
  - c'est $\texttt{Python}$ qui le garantit: il ne retient que les éléments distincts

In [5]:
{42, 11, 38, 42, 42, 42, 2001}

{11, 38, 42, 2001}

### Test d'appartenance  
En mathématique, si un élément $e$ appartient à un ensemble $E$ on note : $e \in E$.  
En $\texttt{Python}$, ceci se traduit par une expression d'appartenance de $\texttt{type bool}$  

**Test d'appartenance**  
L'expression $\texttt{<elem>} \,\, \texttt{in}\,\,  \texttt{<ensemble>}$  $\qquad$ où :
$\texttt{<elem>}$ de $\texttt{type}\, \alpha$ ; $\texttt{<ensemble>}$ de $\texttt{type} \, \texttt{set}[\alpha]$  
teste l'appartenance de l'élément $\texttt{<elem>}$ dans l'ensemble $\texttt{<ensemble>}$, i.e. :  
• renvoie $\texttt{True}$ si $\texttt{<elem>}$ appartient à $\texttt{<ensemble>}$  
• renvoie $\texttt{False}$ sinon  

**Non appartenance** 
L'expression $\texttt{<elem>} \,\, \texttt{not in}  \texttt{<ensemble>}$  
teste la non appartenance de l’élément $\texttt{<elem>}$ dans l’ensemble $\texttt{<ensemble>}$.  

Exemples :

In [6]:
124 in set(),124 in {9, 124, 2},'b' not in {'c', 'a'}

(False, True, True)

L'intérêt majeur du test d'appartenance (ou de non-appartenance) sur les ensembles en $\texttt{Python}$  est qu'il est d'une grande efficacité.  

Si l'on compare aux listes, il faut (**dans le pire cas**) de l'ordre de $n$ tests d'égalité pour vérifier si
un élement appartient à une liste de longueur $n$ alors que dans la plupart des cas un seul test suffit pour répondre à la même question dans le cas d'un ensemble de $n$ éléments.

### Modification d'un ensemble  
**Ajout d'éléments**  
L'ajout d'un élément $\texttt{<elem>}$ de $\texttt{type}\, \alpha$ à un ensemble de $\texttt{type} \, \texttt{set}[\alpha]$   
se fait par :  $\texttt{<ensemble>}.\texttt{add}(\texttt{<elem>})$  

Le **principe d'interprétation** est : 
1. évaluation de l’expression $\texttt{<elem>}$
2. ajout, par **mutation**, de la valeur à l'ensemble $\texttt{<ensemble>}$  

Le **principe d'interprétation** associé est la **modification** de l'$\texttt{<ensemble>}$ pour ajouter l'$\texttt{<elem>}$. Cette modification se fait par **effet de bord** c'est-à-dire directement en mémoire,
sans reconstruction d'un ensemble résultat. Aucune valeur n'est ainsi retournée par la **méthode** $\texttt{add}$.  

### Modification d’un ensemble
**Remarques :**  
• Opérations très efficaces (temps constant) car on ne reconstruit pas l'ensemble  
• Valeur de retour : $\texttt{None}$ (effet de bord, comme la fonction append $\ldots$)  
• Type de $\texttt{<elem>}$ doit être compatible avec celui de $\texttt{<ensemble>}$.  
• Ajout d'un élément déjà présent : rien ne se passe  

Exemple :

In [7]:
E = {2, 1, 4}

In [8]:
E.add(2+1),E.add(4),E

(None, None, {1, 2, 3, 4})

### Complément : retrait d'un élément  
L'opération complémentaire de retrait d'un élément dans un ensemble est également disponible. Si le retrait d'un élément dans une liste est coûteux, il s'agit d'une opération très efficace sur les ensembles.  
On utilise dans ce cas la **méthode** $\texttt{remove}$ selon la syntaxe :  
$\texttt{<ensemble>}.\texttt{remove}(\texttt{<elem>})$

In [9]:
E.remove(3),E

(None, {1, 2, 4})

### Exemple : $\texttt{presences}$  
**Problème**  
Étant donnée une liste d'éléments, construire l'ensemble des éléments de cette liste.  
Étant donnée une liste $L$ d'entiers la fonction $\texttt{presences}$ retourne l'ensemble des entiers qui apparaissent au moins une fois dans $L$.  

• un élément n'est ajouté qu'une seule fois  
• l'ensemble résultat doit être initialisé à l'ensemble vide

In [10]:
def presences(L) :
    """list[int] -> set[int]
    retourne ensemble des entiers qui apparaissent au moins une fois dans L."""
    # E : set[int]
    E = set() # ensemble resultat, initialement vide
    for n in L :
        E.add(n)
    return E

# Jeu de tests
assert presences([9,11, 11, 2, 5, 9, 2, 2, 1, 3]) == {1, 2, 3, 5, 9, 11}
assert presences([1,2, 3, 4]) == {1, 2, 3, 4}
assert presences([2,2, 2, 2]) == {2}
assert presences([])== set()

### Itération sur les ensembles  
• Un ensemble n'est pas une séquence  
• Mais on peut réaliser une itération sur les éléments d'un ensemble  

**Itération sur les ensembles**  
$\texttt{#<var> : alpha}$  
$\texttt{for}\,\, \texttt{<var>} \,\, \texttt{in} \,\, \texttt{<ensemble>}\, \texttt{:}$  
$\phantom{.} \quad \texttt{<corps>}$  

• $\texttt{<var>}$ : variable d'itération d'élément de $\texttt{type}\, \alpha$  
• $\texttt{<ensemble>}$ : un ensemble d'éléments de $\texttt{type} \, \texttt{set}[\alpha]$  
• $\texttt{<corps>}$ : suite d'instructions  

**Principe d'interprétation**  
• le $\texttt{<corps>}$ est exécuté une fois pour chaque élément de $\texttt{<ensemble>}$  
• $\texttt{<var>}$ contient l'élément concerné  
• $\texttt{<var>}$ n'est plus utilisable à la sortie de la boucle  

### Itération sur les ensembles  
**Attention :** l'ordre d'itération est arbitraire  
• aucune garantie sur l'ordre de traitement des éléments  
• seule garantie : tous les élements seront vus une et une seule fois

### Exemple : somme  
**Problème**  
Étant donnée un ensemble d'éléments, calculer la somme de ces éléments.

In [11]:
def somme_ensemble(E) :
    """set[int] -> int
    Renvoie la somme des éléments de E."""
    # s : int
    s = 0 # somme
    # n : int (element courant)
    for n in E :
        s = s + n
    return s

# Jeu de tests
assert somme_ensemble({1, 3, 9, 24, 5}) == 42
assert somme_ensemble({1, 3, 1, 9, 3, 24, 5, 24, 5}) == 42
assert somme_ensemble({-2, -1, 0, 1, 2}) == 0
assert somme_ensemble(set()) == 0
{1, 3, 9, 24, 5} == {1, 3, 1, 9, 3, 24, 5, 24, 5}

True

### Comparaison d'ensembles  
**Sous-ensemble** : $E_1 \subseteq E_2$  
• un ensemble $E_1$ est un sous-ensemble de $E_2$ si tout élément de $E_1$ est un élément de $E_2$  

In [12]:
def est_sous_ensemble(E1, E2) :
    """set[alpha] * set[alpha] -> bool
    Renvoie True si E1 est sous-ensemble de E2, False Sinon."""
    # e : alpha (element courant)
    for e in E1 :
        if e not in E2 :
            return False
    return True

# Jeu de tests
assert est_sous_ensemble({2, 5}, {2, 5, 9}) == True
assert est_sous_ensemble({5}, {2, 5, 9}) == True
assert est_sous_ensemble(set(), {2, 5, 9}) == True
assert est_sous_ensemble({2, 8}, {2, 5, 9}) == False

Cette relation sous-ensemble correspond en fait à l'odre naturel sur les ensembles, et donc en $\texttt{Python }$ plutôt que d'écrire : $\texttt{est\_sous\_ensemble}(E1, E2)$ 
On peut utiliser de façon équivalente (et préférée) $E1 <= E2$  

• en Python: expression qui rend $\texttt{True}$ si $E_1 \subseteq E_2$  

Par exemple :

In [13]:
{2, 5} <= {2, 5, 9},{5} <= {2, 5, 9},set() <= {2, 5, 9},{2, 8} <= {2, 5, 9}

(True, True, True, False)

### Autres comparateurs  
**Sous-ensemble strict** : $E_1 \subset E_2$   $\qquad$ $E1 <  E2\, \, $ ou bien : $\, \,E2  >  E1$  
**Egalité** de deux ensembles : $E1 == E2$ $\,$ → $\texttt{True}$ si on a $E_1 \subseteq E_2$ **et** $E_2 \subseteq E_1$  
**Inégalité** de deux ensembles : $E1 != E2$

In [14]:
{5, 2, 9} == {2, 5, 9},{5, 2, 9} != {2, 5, 9},{5, 2} == {2, 5, 9},{5, 2} != {2, 5, 9}

(True, False, False, True)

### Opérations ensemblistes (1)   
Pour terminer notre introduction aux ensembles, nous allons présenter les opérations ensemblistes les plus  fondamentales : l'union, l'intersection et la différence entre deux ensembles.  

**Union** de deux ensembles : $E_1 \cup E_2$  
• ensemble des éléments de $E_1$ et de $E_2$

In [15]:
def union(E1, E2):
    """set[alpha] * set[alpha] -> set[alpha]
    Retourne union des ensembles E1 et E2."""
    # U : set[alpha]
    U = set() # ensemble resultat  
    # e1 : alpha (element de E1)
    for e1 in E1 :
        U.add(e1)
    # e2 : alpha (element de E2)
    for e2 in E2 :
        U.add(e2)
    return U

# Jeu de test
assert union({'a','e','u'}, {'o','i'}) == {'a', 'e', 'i', 'o', 'u'}
assert union({2, 5, 9}, {1, 3, 4,8}) == {1, 2, 3, 4, 5, 8, 9}
assert union({1, 2, 5, 9}, {1, 3,4, 8}) == {1, 2, 3, 4, 5, 8, 9}
assert union({1, 2, 5, 9}, set())== {1, 2, 5, 9}
assert union(set(), {1, 2, 5, 9})== {1, 2, 5, 9}

L'union ensembliste est une opération fondamentale, et ce n'est donc pas étonnant de la trouver prédéfinie en $\texttt{Python}$.  

• Il existe une instruction Python : $\mid$

In [16]:
{1, 2, 3} | {3, 4}

{1, 2, 3, 4}

### Opérations ensemblistes (2)   
L'intersection ensembliste est également une opération courante dans la vie de tous les jours. 

**Intersection** de deux ensembles : $E_1 \cap E_2$  
• ensemble des éléments qui sont à la fois dans $E_1$ et dans $E_2$

In [17]:
def intersection(E1, E2) :
    """set[alpha] * set[alpha] -> set[alpha]
    Retourne intersection des ensembles E1 et E2."""
    # I : set[alpha]
    I = set() # ensemble intersection
    # e1 : alpha (element de E1)
    for e1 in E1 :
        if e1 in E2 :
            I.add(e1)
    return I

# Jeu de tests
assert intersection({'a', 'i','o'}, {'u', 'i', 'o', 'y'}) == {'o', 'i'}
assert intersection({2, 5, 9},{1, 2, 3, 4, 5, 8}) == {2, 5}
assert intersection({2, 5, 9},{2, 3, 4, 8}) == {2}
assert intersection({2, 5, 9},{1, 3, 4, 8}) == set()
assert intersection({2, 5, 9}, set()) == set()
assert intersection(set(), {2, 5, 9}) == set()

• Il existe une instruction Python : $\&$

In [18]:
{1, 2, 3} & {3, 4}

{3}

## Opérations ensemblistes (3)  
**Différence** de deux ensembles : $E_1 \setminus E_2$  
• ensemble des éléments de $E_1$ qui ne sont pas dans $E_2$

In [19]:
def difference(E1, E2) :
    """set[alpha] * set[alpha] -> set[alpha]
    Retourne la difference des ensembles E1 et E2."""
    # D : set[alpha]
    D = set() # ensemble difference
    # e1 : alpha (element de E1)
    for e1 in E1:
        if e1 not in E2:
            D.add(e1)
    return D

# Jeu de tests
assert difference({'a', 'i', 'o', 'y'}, {'u', 'i', 'o'}) == {'a', 'y'}
assert difference({ 2, 5, 9 }, {2, 3, 4, 8}) == {5, 9}
assert difference({ 2, 5, 9 }, {2, 3, 5, 8}) == {9}
assert difference({ 2, 5, 9 }, {2, 3, 5, 8, 9}) == set()
assert difference({ 2, 5, 9 }, {2, 5, 9}) == set()
assert difference({2, 5, 9}, set()) == {2, 5, 9}
assert difference(set(), {2, 5, 9}) == set()

• Il existe une instruction Python : $-$  

In [20]:
{1, 2, 3} - {3, 4}

{1, 2}

### Les dictionnaires  

Les dictionnaires sont sans doute, avec les listes, les structures de données les plus couramment
utilisées en $\texttt{Python}$.  
Un dictionnaire $\texttt{Python}$ exprime une relation entre un ensemble de clés - dites de recherche - et un ensemble de valeurs.  
Cette relation est mathématiquement une application (un *mapping*) qui impose qu'à chaque clé corresponde exactement une valeur.  
On dit que le couple formé d'une clé et de sa valeur associée forme une association.

* Une **association** : liaison entre une **clé de recherche** et une **valeur** associée  
* **Dictionnaire** : ensemble d'associations entre  
  - une clé de $\texttt{type}\, \alpha$  
  - une valeur de $\texttt{type}\, \beta$  
* Les clés sont **uniques** : pas de doublons (comme les ensembles)
* $\texttt{Type}$ d'un dictionnaire: $\texttt{dict}[\alpha : \beta]$  
  - en fait pas tous les $\alpha$, uniquement les **objets immutables** ($\texttt{str}$, $\texttt{Number}$, $\texttt{int}$) mais pas les $\texttt{listes}$ !)
* Par exemple  
  - $\texttt{'pi'}$ est associée à la valeur $3.14159265$  
  - $\texttt{'rcarre2'}$ est associée à la valeur $1.41421356237$  
  - $\texttt{'phi'}$ est associée à la valeur $1.6180339887$  
  
On remarque la proximité entre la notion d'ensemble et celle de dictionnaire. En effet, les clés du dictionnaires forment un ensemble au sens de ce que nous avons présenté dans la première partie du cours.  
Exemple - un dictionnaire (très partiel) des constantes mathématiques :

In [21]:
{'pi' : 3.14159265, 'sqrt2' : 1.41421356237, 'phi' : 1.6180339887 }

{'pi': 3.14159265, 'sqrt2': 1.41421356237, 'phi': 1.6180339887}

Le $\texttt{type}$ de ce dictionnaire est $\texttt{dict}[\texttt{str}:\texttt{float}]$ c'est-à-dire une association entre :  
- des noms de constantes mathématiques représentées par des chaînes de caractères pour les clés  
- et leur valeur numérique sous la forme d'un flottant.  

Avant de passer à la suite, nous allons conserver notre dictionnaire des constantes en l'affectant à une variable permettant de le référencer dans les exemples.  

In [22]:
# Consts : dict[str:float]
Constantes = {'pi' : 3.14159265,'sqrt2' : 1.41421356237,'phi' : 1.6180339887 }

### Construction de dictionnaires  
* Construction explicite: on énonce tous les éléments $\left\{k_1 : v_1 , k_2 : v_2 , \ldots , k_N : v_N\right\}$  
  - les $k_1 , k_2 , \ldots , k_N$ : expressions pour les clés de $\texttt{type}\, \alpha$   
  - les $v_1 , v_2 , \ldots , v_N$ : expressions pour les valeurs $\texttt{type}\, \alpha$   
* Construction du dictionnaire vide $\quad \texttt{dict}(\,)$
* Liaisons créées  
  - la valeur $v_1$ est associée à la clé $k_1$, etc.  
* Exemple: dictionnaire de $\texttt{type}$ $\texttt{dict}[\texttt{str}:\texttt{float}]$

In [23]:
# Consts : dict[str:float]
Constantes

{'pi': 3.14159265, 'sqrt2': 1.41421356237, 'phi': 1.6180339887}

### Accès aux valeurs  
Lorsque nous utilisons un dictionnaire commun, le cas d'utilisation typique est de rechercher une
définition à partir d'un mot. Transposé en termes de dictionnaire $\texttt{Python}$, ce cas d'utilisation consiste à recherche une valeur à partir de sa clé.  

* Accès à une valeur : on utilise la clé de recherche comme référence  
  - syntaxe: $\texttt{<dictionnaire>}[\texttt{<cle>}]$  
  - $\texttt{<dictionnaire>}$ est un dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$  
  - $\texttt{<cle>}$ est une expression de $\texttt{type}\, \alpha$   
* Dans un dictionnaire :  
  - seule la clé permet d'accéder à une liaison
  - **Attention** : la clé doit être présente dans le dictionnaire  
    Remarque : il faudra donc savoir à l'avance si une clé est présente ou non dans un dictionnaire $\ldots$
* Exemples  

In [24]:
Constantes['pi']
Constantes['e']

KeyError: 'e'

### Test d'appartenance d'une clé  
Nous l'avons vu ci-dessus, avant de pouvoir accéder à une valeur associée à une clé dans un dictionnaire, il faut préalablement vérifier si cette clé est bien présente. Si l'on construit explicitement le dictionnaire alors on peut déduire cette information simplement, mais si le dictionnaire est construit de façon algorithmique alors il est nécessaire de pouvoir tester l'appartenance d'une clé à un dictionnaire.  

* Présence d'une clé dans un dictionnaire  $\texttt{<cle>} \,\, \texttt{in} \,\, \texttt{<dictionnaire>}$  
  - $\texttt{<dictionnaire>}$ est un dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$  
  - $\texttt{<cle>}$ est une expression de $\texttt{type}\, \alpha$   
* **Principe d'évaluation**
  - $\texttt{True}$ si la $\texttt{<cle>}$  existe dans $\texttt{<dictionnaire>}$  
  - $\texttt{False}$ sinon  
* Non appartenance : $\quad \texttt{<cle>}\,\, \texttt{not in} \,\, \texttt{<dictionnaire>}$

In [25]:
'pi' in Constantes,'pi' not in Constantes,'e' in Constantes,'e' not in Constantes

(True, False, False, True)

**Remarque :** le test d'appartenance d'une clé à un dictionnaire revient à tester l'appartenance de cette clé à l'ensemble des clés du dictionnaire, il s'agit donc d'une opération très efficace.

### Ajout d'une association  
* Ajout d'une association $\quad \texttt{<dictionnaire>}[\texttt{<cle>}] = \texttt{<valeur>}$  
* **Principe d'interprétation**  
  - si la $\texttt{<cle>}$ n'appartient pas au dictionnaire, l'association $\texttt{<cle> : <valeur>}$ est rajoutée au dictionnaire (- ajout par effet de bord -)  
  - sinon, si la $\texttt{<cle>}$ appartient au dictionnaire, la valeur associée précédente est remplacée par $\texttt{<valeur>}$

In [26]:
Constantes['e'] = 2.71828182
Constantes


{'pi': 3.14159265,
 'sqrt2': 1.41421356237,
 'phi': 1.6180339887,
 'e': 2.71828182}

### Dictionnaire $\texttt{vs.}$ Listes  
On aurait pu utiliser une liste d'associations :  
> $\texttt{Const\_dict}=\left\{\texttt{'pi' : 3.14159265 , 'rcarre2' : 1.41421356237 , 'phi' : 1.6180339887}\right\}$
> $\texttt{Const\_list}=[(\texttt{'pi', 3.14159265}) , (\texttt{'rcarre2', 1.41421356237}) , (\texttt{'phi', 1.6180339887})]$

Quel coût cela aurait-il de :  
• Vérifier si $\texttt{'e'}$ est une clef présente  
• Récupérer la valeur associée à $\texttt{'phi'}$   
• Ajouter (où ?) une nouvelle association entre $\texttt{'e'}$ et $\texttt{2.718281828}$

Les dictionnaires sont très efficaces pour effectuer ces opérations  
<img src="./images/dict.png" alt="dictionnaire"/>

### Exemple : comptage d'occurrences  
L'instruction d'ajout/remplacement dans un dictionnaire nous permet d'effectuer des constructions algorithmiques.  Un cas d’utilisation typique des dictionnaires consiste à compter les occurrences des éléments d'une liste.  

**Problème** 
Calculer le nombre d'occurrences de chacune des lettres d'une chaı̂ne de caractères données.

In [27]:
def compte_occurrences(L) :
    """ list[str] -> dict[str:int]
    retourne le compte des occurrences des elements de la liste L."""
    # D : dict[str:int]
    D = dict() # le dictionnaire resultat
    # e : str (element courant)
    for e in L :
        if e not in D: # premiere occurrence
            D[e] = 1
        else: # k-ieme occurrence, k > 1
            D[e] = D[e] + 1
    return D

# Jeu de tests
assert compte_occurrences(['b','c','e','b','c','j','d','b','j','a','b'])\
== {'b' : 4, 'c': 2, 'e': 1, 'j': 2, 'd': 1, 'a':1 }
assert compte_occurrences(['a', 'a', 'a', 'a', 'a']) == {'a' : 5}
assert compte_occurrences([]) == dict()
#compte_occurrences(list('anticonstitutionnellement')) 

**Question** : la signature de la fonction compte_occurrences est-elle la plus générale possible ?

In [28]:
def compte_occurrences_str(L) :
    """str -> dict[str:int]
    retourne le compte des occurrences des elements de la liste L."""
    # D : dict[str:int]
    D = dict() # le dictionnaire resultat
    # e : str (element courant)
    for e in L :
        if e not in D: # premiere occurrence
            D[e] = 1
        else: # k-ieme occurrence, k > 1
            D[e] = D[e] + 1
    return D

compte_occurrences('anticonstitutionnellement')

{'a': 1,
 'n': 5,
 't': 5,
 'i': 3,
 'c': 1,
 'o': 2,
 's': 1,
 'u': 1,
 'e': 3,
 'l': 2,
 'm': 1}

### Complément : retrait d'une assocation  
De façon symétrique à l'ajout, il est possible de supprimer une association d'un dictionnaire.  
On utilise pour cela la syntaxe suivante :  $\texttt{del} \,\, \texttt{<dictionnaire>}[\texttt{<cle>}]$  
où  
* $\texttt{<dictionnaire>}$ est une expression de dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$    
* $\texttt{<cle>}$ est une expression de $\texttt{type}\, \alpha$  

In [29]:
# Consts : dict[str:float]
# Constantes = {'pi' : 3.14159265,'sqrt2' : 1.41421356237,'phi' : 1.6180339887 }
del Constantes['sqrt2']
Constantes

{'pi': 3.14159265, 'phi': 1.6180339887, 'e': 2.71828182}

In [30]:
del Constantes['sqrt2']

KeyError: 'sqrt2'

### Itération sur un dictionnaire  
Après avoir construit un dictionnaire, une opération très courante consiste à le parcourir intégralement. Il n'est donc pas étonnant que les concepteurs du langage $\texttt{Python}$ aient prévu d'étendre la boucle $\texttt{for}$  d'itération pour répondre à ce besoin.  
En fait, il existe deux types de boucles d'itérations sur les dictionnaires :  
- l'itération sur les clés du dictionnaire,  
- l'itération sur les associations clé/valeur.

### Itération sur les clés du dictionnaire   
**Itération sur les clés**  
• Syntaxe de l'itération **sur les clés**    
$\texttt{# <var> : alpha}$  
$\texttt{for <var> in <dictionnaire> :}$  
$\phantom{.} \qquad \texttt{<corps>}$

• $\texttt{<var>}$ : variable d'itération sur les clés de $\texttt{type}\, \alpha$  
• $\texttt{<dictionnaire>}$ : un dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$   
• $\texttt{<corps>}$ : suite d'instructions

### Exemple d'itération  
**Problème**  
Étant donné un dictionnaire, écrire une fonction qui renvoie l'ensemble des clefs de ce dictionnaire.

In [31]:
def ensemble_des_cles(D) :
    """dict[alpha:beta] -> set[alpha]
    Renvoie ensemble des cles du dictionnaire D."""
    # K : set[alpha]
    K = set()
    # k : alpha (cle courante)
    for k in D :
        K.add(k)
    return K

# Jeu de tests
assert ensemble_des_cles({'a':1, 'z':26, 't':20, 'q':17}) \
== {'a', 'q', 't', 'z'}
assert ensemble_des_cles({'e':2.71828182,'pi':3.141592653589793,'phi':1.6180339887})\
== {'e', 'pi', 'phi'}
assert ensemble_des_cles(dict()) == set()
#{'a':1, 'z':26, 't':20, 'q':17}.keys()

Comme vous le voyez, **si on essaye de parcourir un dictionnaire « simplement », on parcourt en réalité la liste des clés contenues dans le dictionnaire**.  

Mais… les clés peuvent ne pas s'afficher pas dans l'ordre dans lequel on les a entrées… c'est normal ?  
Les dictionnaires n'ont pas de structure ordonnée, gardez-le à l'esprit. Donc en ce sens oui, c'est tout à fait normal.

### Comment récupérer les clés d'un dictionnaire $\texttt{Python}$ par une boucle ?  

Une méthode de la classe $\texttt{dict}$ permet d'obtenir ce même résultat.  
Personnellement, je l'utilise plus fréquemment car on est sûr, en lisant l'instruction, que c'est la liste des clés que l'on parcourt.  
La méthode $\texttt{keys}()$  renvoie une **séquence** (qui est donc itérable) **des clés** contenues dans le dictionnaire où on l'applique.

Pour récupérer les clés on utilise la **méthode** $\texttt{keys}()$ .  

$\texttt{#<cle> : alpha}$  
$\texttt{for}\,\, \texttt{<cle>} \,\, \texttt{in} \,\, \texttt{<dictionnaire>}.\texttt{keys}()\, \texttt{:}$  
$\phantom{.} \quad \texttt{<corps>}$  

• $\texttt{<cle>}$ : variable d'itération sur les clés de $\texttt{type}\, \alpha$  
• $\texttt{<dictionnaire>}$ : un dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$   
• $\texttt{<corps>}$ : suite d'instructions utilisant la $\texttt{<cle>}$ courante

In [32]:
def ensemble_des_cles(D) :
    """dict[alpha:beta] -> set[alpha]
    Renvoie ensemble des cles du dictionnaire D."""
    # K : set[alpha]
    K = set()
    # k : alpha (cle courante)
    for k in D.keys():
        K.add(k)
    return K

# Jeu de tests
assert ensemble_des_cles({'a':1, 'z':26, 't':20, 'q':17}) \
== {'a', 'q', 't', 'z'}
assert ensemble_des_cles({'e':2.71828182,'pi':3.141592653589793,'phi':1.6180339887})\
== {'e', 'pi', 'phi'}
assert ensemble_des_cles(dict()) == set()

### Exemple : liste des valeurs  
**Problème** 
Étant donné un dictionnaire, écrire une fonction qui renvoie la liste des valeurs de ce dictionnaire.

In [33]:
def liste_des_valeurs(D) :
    """ dict[alpha:beta] −> list[beta]
    Renvoie la liste des valeurs du dictionnaire D."""
    # L : list[beta]
    L = []
    # k : alpha (clef courante)
    for k in D :
        L.append(D[k])
    return L

# Jeu de tests
assert liste_des_valeurs({'a':1, 'z':26, 't':20, 'q':17}) \
== [1, 26, 20, 17]
assert liste_des_valeurs({'e':2.71828182,'pi':3.141592653589793,'phi':1.6180339887})\
== [2.71828182, 3.141592653589793, 1.6180339887]
assert liste_des_valeurs(dict()) == []

**Notez bien**, comme il est possible de construire cette liste $L$ avant de la renvoyer :  
(la valeur du dictionnaire $D$ associée à la clé courante $k$)  $\longleftrightarrow$  $D[k]$  
**Remarque :** le premier cas de test est très «fragile » car il dépend de l'ordre dans lequel les associations du dictionnaire sont parcourues. D'un ordinateur à un autre, et d'une version de $\texttt{Python}$ à une autre, cet ordre a de fortes chances de changer. Ceci illustre que la récupération des valeurs d'un dictionnaire n'est pas une opération triviale.

### Comment récupérer les valeurs d'un dictionnaire $\texttt{Python}$ par une boucle ?   
Cette méthode est peu utilisée pour un parcours car il est plus pratique de parcourir la liste des clés, cela suffit pour avoir les valeurs correspondantes. Mais on peut aussi, bien entendu, **l'utiliser dans une condition**.

Pour récupérer les valeurs on utilise la **méthode** $\texttt{values}()$ .  

$\texttt{#<valeur> : beta}$  
$\texttt{for}\,\, \texttt{<valeur>} \,\, \texttt{in} \,\, \texttt{<dictionnaire>}.\texttt{values}()\, \texttt{:}$  
$\phantom{.} \quad \texttt{<corps>}$  

• $\texttt{<valeur>}$ : variable d'itération sur les valeurs de $\texttt{type}\, \beta$  
• $\texttt{<dictionnaire>}$ : un dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$   
• $\texttt{<corps>}$ : suite d'instructions utilisant la $\texttt{<valeur>}$ courante

In [34]:
def liste_des_valeurs(D) :
    """ dict[alpha:beta] −> list[beta]
    Renvoie la liste des valeurs du dictionnaire D."""
    # L : list[beta]
    L = []
    # k : beta (valeur courante)
    for k in D.values() :
        L.append(k)
    return L

# Jeu de tests
assert liste_des_valeurs({'a':1, 'z':26, 't':20, 'q':17}) \
== [1, 26, 20, 17]
assert liste_des_valeurs({'e':2.71828182,'pi':3.141592653589793,'phi':1.6180339887})\
== [2.71828182, 3.141592653589793, 1.6180339887]
assert liste_des_valeurs(dict()) == []

In [35]:
if 3.14159265 in Constantes.values():
    print("Une des constantes mathématiques est une valeur approchée de pi.")

Une des constantes mathématiques est une valeur approchée de pi.


### Itération sur les associations du dictionnaire - Parcours des clés et valeurs simultanément
Dans des cas un peu moins fréquents, on peut s'intéresser au parcours des associations $\texttt{cle/valeur}$ dans un dictionnaire.  
**Itération sur les associations**  
• Syntaxe de l'itération **sur les associations**    
$\texttt{#}\,\, (\texttt{cvar , vvar}) : \texttt{tuple[alpha , beta]}$  
$\texttt{for} \,\, (\texttt{<cvar>, <vvar>}) \,\, \texttt{in <dictionnaire>.items}() :$  
$\phantom{.} \qquad \texttt{<corps>}$

• $\texttt{<cvar>}$ : variable ditération sur les clés de $\texttt{type}\, \alpha$  
• $\texttt{<vvar>}$ : variable ditération sur les clés de $\texttt{type}\, \beta$  
• $\texttt{<dictionnaire>}$ : un dictionnaire de $\texttt{type}$ $\texttt{dict}[\alpha : \beta]$   
• $\texttt{<corps>}$ : suite d'instructions  


**Principe d'interprétation**  
• le $\texttt{<corps>}$ est exécuté pour chaque association du dictionnaire  
• à chaque tour de boucle, la variable $\texttt{<cvar>}$ est liée à la clé de l'association et la variable $\texttt{<vvar>}$ est liée à la valeur associée  
• les variables $\texttt{<cvar>}$ et $\texttt{<vvar>}$ ne sont plus utilisables après le dernier tour de boucle

### Retour sur l'exemple : liste des valeurs  
**Problème** 
Étant donné un dictionnaire, écrire une fonction qui renvoie la liste des valeurs de ce dictionnaire.

In [36]:
def liste_des_valeurs(D) :
    """dict[alpha:beta] −> list[beta]
    Renvoie la liste des valeurs du dictionnaire D."""
    # L : list[beta]
    L = []
    # (k, v) : tuple[alpha, beta] (couple courant)
    for (k, v) in D.items() :
        L.append(v)
    return L

# Jeu de tests
assert liste_des_valeurs({'a':1, 'z':26, 't':20, 'q':17}) \
== [1, 26, 20, 17]
assert liste_des_valeurs({'e':2.71828182,'pi':3.141592653589793,'phi':1.6180339887})\
== [2.71828182, 3.141592653589793, 1.6180339887]
assert liste_des_valeurs(dict()) == []

>D'un point de vue stylistique, on peut trouver l'itération sur les associations un peu plus lisible et elle est de fait légèrement plus efficace (on n'a pas besoin de «chercher» la valeur).  

**Remarque :** le premier cas de test est très «fragile » car il dépend de l'ordre dans lequel les associations du dictionnaire sont parcourues. La récupération des valeurs d'un dictionnaire n'est pas une opération triviale.

### Exemple complet : livre de recettes   
On aimerait pouvoir manipuler un livre de recettes numérique, comme par exemple le livre de desserts suivant :

| Recette | Ingrédients |
|:-------:|:-----------:|
| Gâteau au chocolat | chocolat, œuf, farine, sucre, beurre |
| Gâteau au yaourt | yaourt, œuf, farine, sucre |
| Crêpes | œuf, farine, lait |
| Quatre-quarts | œuf, farine, beurre, sucre |
| Kouign amann | farine, beurre, sucre |

Comment représenter l’information ? $\texttt{dict}[\texttt{str}:\texttt{set}[\texttt{str}]]$

In [37]:
Dessert = {
'gateau chocolat' : {'chocolat', 'oeuf', 'farine', 'sucre', 'beurre'},
'gateau yaourt' : {'yaourt', 'oeuf', 'farine', 'sucre'},
'crepes' : {'oeuf', 'farine', 'lait'},
'quatre-quarts' : {'oeuf', 'farine', 'beurre', 'sucre'},
'kouign amann' : {'farine', 'beurre', 'sucre'}}

### Exemple complet: livre de recettes  
Écrire les fonctions permettant de :  
1. connaı̂tre le nombre d'ingrédients utilisés par une recette
2. connaı̂tre l'ensemble des ingrédients mentionnés
3. contruire la table des ingrédients
4. connaı̂tre l'ingrédient le plus utilisé
5. connaı̂tre les recettes utilisant un ingrédient donné
6. connaı̂tre les recettes réalisables étant donné un ensemble d'ingrédients
7. construire un livre de recettes qui n'utilisent pas un ingrédient donné
8. $\ldots$  

Etant donnés deux livres de recettes, écrire les fonctions permettant de :  
1. connaı̂tre l'ensemble des ingrédients mentionnés dans ces livres
2. connaı̂tre l'ensemble des recettes redondantes (identiques)
3. connaı̂tre l'ensemble des recettes incohérentes
4. construire le livre de recettes communes avec leurs variantes
5. $\ldots$ 

### Nombre d’ingrédients utilisés par une recette  
1. Fonction qui étant donné un livre de recettes et une recette retourne le nombre d'ingrédients utilisés par la recette,   
  $0$ si la recette n'est pas dans le livre.

In [38]:
def nb_ingredients(D, r) :
    """dict[str:set[str ]] ∗ str −> int
    retourne le nombre ingredients dans la recette r si elle est dans D, 0 sinon"""
    # res : int
    res = 0
    # r : str
    if r in D :
        # s : str
        for s in D[r] :
            res = res + 1
    return res

# Jeu de tests
assert nb_ingredients(Dessert, 'gateau chocolat') == 5
assert nb_ingredients(Dessert, 'crepes') == 3
assert nb_ingredients(Dessert, 'flan') == 0

### Ensemble des ingrédients mentionnés  
2. Fonction qui étant donné un livre de recettes retourne l'ensemble des ingrédients utilisés dans le livre de recettes

In [39]:
def ensemble_ing(D) :
    """dict[str:set[str ]] −> set[str]
    retourne ensemble des ingredients apparaissant dans les recettes"""
    # E : set[str]
    E = set()
    # r : str 
    # Eingr: set[str]
    for r, Eingr in D.items() :
        E = E | Eingr
    return E

#
assert ensemble_ing(Dessert) \
== {'chocolat', 'oeuf', 'farine', 'sucre', 'beurre', 'yaourt', 'lait'}

### Ensemble des recettes avec un ingrédient
...

5. Fonction qui étant donné un livre de recettes et un ingrédient retourne l'ensemble des recettes utilisant  l'ingrédient.

In [40]:
def ensemble_recette(ingr , D) :
    """str ∗ dict[str:set[str ]] −> set[str]
    retourne ensemble des recettes utilisant ingredient ingr"""
    # E : set[str]
    E = set()
    # r : str
    # Er : set[str]
    for r, Er in D.items() :
        if ingr in Er :
            E.add(r)
    return E

# Jeu de tests
assert ensemble_recette('chocolat', Dessert) == {'gateau chocolat'}
assert ensemble_recette('pistache', Dessert) == set()
assert ensemble_recette('beurre', Dessert) == {'gateau chocolat', 'quatre-quarts', 'kouign amann'}
assert ensemble_recette('sucre', Dessert) \
== {'gateau chocolat', 'quatre-quarts', 'kouign amann', 'gateau yaourt'}

### Conclusion  
Ce qu'il faut savoir faire à l'issue de cette partie :  (retenir/utiliser)
* Notion d'ensembles :  
  * contruction - modification - itération 
  * opérations ensemblistes de base
* Les **$p-$uplets nommés** permettent les enregistrements de valeurs de types différents dans des champs nommés
* En $\texttt{Python}$, les **$p-$uplets nommés** sont implémentés par des dictionnaires. 
* Les <a href="https://pixees.fr/informatiquelycee/n_site/snt_photo_exif.html" target="_blank">données $\texttt{EXIF}$ </a> d'une image peuvent-être présentées sous la forme d'un enregistrement ($\texttt{dict}$).    
* Dictionnaires par clés et valeurs  
  * Construire une entrée de dictionnaire.
  * Itérer sur les éléments d'un dictionnaire
  * Utiliser les méthodes $\texttt{keys}()$, $\texttt{values}()$ et $\texttt{items}()$.


**Rappel :**  
* En $\texttt{Python}$, les **$p-$uplets nommés** sont implémentés par des dictionnaires.  
* La structure **itérable** - Nous avons vu que les 3 structures de données "listes, $n-$uplets et chaı̂nes de caractères" sont des cas particuliers d'une structure plus générale qu'on appelle un **itérable**. Il s'agit dans les 3 cas, d'une **collection ordonnée de valeurs que l'on peut parcourir** (en particulier à l'aide d'une boucle $\texttt{for}$). Par défaut, un itérable n'a ni la structure de liste, ni de $n-$uplet, ni de chaı̂ne de caractères. 
   On peut cependant facilement convertir (**transtyper**) n'importe quel itérable en :  
   - une liste avec la fonction $\texttt{list}()$  
   - un tuple avec la fonction $\texttt{tuple}()$  
   - une chaı̂ne de caractères avec la fonction $\texttt{str}()$.